### ISSUE TITLE
single test

### ISSUE THREAD

**Issue by Bhanu-Prakash01** [koushikvikram/speech-recognition-deep-learning#1]
how to use model for single test ( basically to prediction)

**Comment by koushikvikram** [comment]
Hi @Bhanu-Prakash01 , thanks for you question!

Please refer to the "Test model on phone numbers" section of the [Jupyter Notebook](https://github.com/koushikvikram/speech-recognition-deep-learning/blob/main/dl-for-speech-recognition.ipynb). It has instructions for prediction on a single audio file.

Thanks,
Koushik Vikram
